"""initial schema

Revision ID: 08520dcaa170
Revises: 
Create Date: 2026-07-30 18:42:31.362393

"""
from alembic import op
import sqlalchemy as sa


revision = '08520dcaa170'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('linkedin_url', sa.String(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('search_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.String(length=300), nullable=False),
    sa.Column('geo_id', sa.String(length=50), nullable=False),
    sa.Column('location_label', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_config_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pages_scraped', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_inserted', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_config_id'], ['search_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_search_config_id'), 'scrape_runs', ['search_config_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('jobs_master',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('linkedin_job_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('job_url', sa.String(length=800), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('search_config_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['search_config_id'], ['search_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_master_company_id'), 'jobs_master', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_master_linkedin_job_id'), 'jobs_master', ['linkedin_job_id'], unique=True)
    op.create_index(op.f('ix_jobs_master_posted_date'), 'jobs_master', ['posted_date'], unique=False)
    op.create_index('ix_jobs_sector_scraped', 'jobs_master', ['sector', 'scraped_at'], unique=False)
    op.create_table('request_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_log_scrape_run_id'), 'request_log', ['scrape_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_log_scrape_run_id'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_index('ix_jobs_sector_scraped', table_name='jobs_master')
    op.drop_index(op.f('ix_jobs_master_posted_date'), table_name='jobs_master')
    op.drop_index(op.f('ix_jobs_master_linkedin_job_id'), table_name='jobs_master')
    op.drop_index(op.f('ix_jobs_master_company_id'), table_name='jobs_master')
    op.drop_table('jobs_master')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_search_config_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_table('search_configs')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
