"""console_log table

Revision ID: 1be3c38600c1
Revises: 08520dcaa170
Create Date: 2026-07-30 20:43:20.042019

"""
from alembic import op
import sqlalchemy as sa


revision = '1be3c38600c1'
down_revision = '08520dcaa170'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_console_log_run_id'), 'console_log', ['run_id'], unique=False)
    op.create_index(op.f('ix_console_log_ts'), 'console_log', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_console_log_ts'), table_name='console_log')
    op.drop_index(op.f('ix_console_log_run_id'), table_name='console_log')
    op.drop_table('console_log')
    # ### end Alembic commands ###
