#!/usr/bin/env bash
# Watch Tower — Cloudflare Tunnel (named) → local VIGIL on 127.0.0.1:8001
# Run on the ThinkPad. Requires: cloudflared, Cloudflare account + zone.
#
# Usage:
#   HOSTNAME=tower.example.com ACCESS_EMAIL=you@example.com \
#     bash scripts/cloudflare_tunnel_setup.sh
#
# Secrets stay under ~/.cloudflared/ (never commit).

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-watch-tower}"
HOSTNAME="${HOSTNAME:-}"
ACCESS_EMAIL="${ACCESS_EMAIL:-}"
LOCAL_URL="${LOCAL_URL:-http://127.0.0.1:8001}"
CF_DIR="${HOME}/.cloudflared"
UNIT_DIR="${HOME}/.config/systemd/user"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

die() { echo "ERROR: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing: $1"; }

need cloudflared
need systemctl

[[ -n "$HOSTNAME" ]] || die "Set HOSTNAME=tower.yourdomain.com (Cloudflare zone DNS)"
[[ -n "$ACCESS_EMAIL" ]] || die "Set ACCESS_EMAIL=you@example.com (Access allowlist)"

mkdir -p "$CF_DIR" "$UNIT_DIR"

echo "[1/6] Cloudflare login (browser will open — pick the zone for $HOSTNAME)"
if [[ ! -f "$CF_DIR/cert.pem" ]]; then
  cloudflared tunnel login
else
  echo "      cert.pem already present — skip login"
fi

echo "[2/6] Create tunnel '$TUNNEL_NAME' (idempotent)"
EXISTING_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')"
if [[ -n "${EXISTING_ID:-}" ]]; then
  TUNNEL_ID="$EXISTING_ID"
  echo "      reuse tunnel id=$TUNNEL_ID"
else
  cloudflared tunnel create "$TUNNEL_NAME"
  TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')"
  [[ -n "$TUNNEL_ID" ]] || die "tunnel create failed — no id for $TUNNEL_NAME"
  echo "      created tunnel id=$TUNNEL_ID"
fi

CRED_FILE="$CF_DIR/${TUNNEL_ID}.json"
[[ -f "$CRED_FILE" ]] || die "missing credentials file: $CRED_FILE"

echo "[3/6] Write config → $CF_DIR/config.yml"
cat > "$CF_DIR/config.yml" <<EOF
# Watch Tower Cloudflare Tunnel — generated by scripts/cloudflare_tunnel_setup.sh
# Do not commit. Points only at loopback (API stays 127.0.0.1).
tunnel: ${TUNNEL_ID}
credentials-file: ${CRED_FILE}

ingress:
  - hostname: ${HOSTNAME}
    service: ${LOCAL_URL}
  - service: http_status:404
EOF

echo "[4/6] Route DNS ${HOSTNAME} → tunnel"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || \
  echo "      DNS route may already exist — check Cloudflare DNS for CNAME $HOSTNAME"

echo "[5/6] Install systemd --user unit watch-tower-tunnel"
cat > "$UNIT_DIR/watch-tower-tunnel.service" <<EOF
[Unit]
Description=Watch Tower Cloudflare Tunnel
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/cloudflared tunnel --config ${CF_DIR}/config.yml run
Restart=on-failure
RestartSec=5
# Keep scrape/API priority; tunnel is light
Nice=5

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now watch-tower-tunnel.service
sleep 2
systemctl --user --no-pager --full status watch-tower-tunnel.service | head -20 || true

echo "[6/6] Access policy checklist (Zero Trust dashboard — do once)"
cat <<EOF

═══════════════════════════════════════════════════════════
  Tunnel running → https://${HOSTNAME}
  Local origin   → ${LOCAL_URL} (unchanged; still loopback-only)

  LOCK IT (Cloudflare Zero Trust → Access → Applications):
  1. Add application → Self-hosted
  2. Application domain: ${HOSTNAME}
  3. Policy name: Ashok only
  4. Action: Allow
  5. Include → Emails → ${ACCESS_EMAIL}
  6. Save. Open https://${HOSTNAME} in any browser → OTP/email gate

  Optional: block /api/docs from public by a second more-restrictive
  Access app path rule, or leave behind Access (same gate).

  Manage:
    systemctl --user status watch-tower-tunnel
    journalctl --user -u watch-tower-tunnel -f
    cloudflared tunnel info ${TUNNEL_NAME}

  Docs: ${REPO_ROOT}/documents/remote-access-cloudflare.md
═══════════════════════════════════════════════════════════
EOF

# Stamp for ops (no secrets)
mkdir -p "${REPO_ROOT}/job_engine/.data"
cat > "${REPO_ROOT}/job_engine/.data/cloudflare_tunnel.json" <<EOF
{
  "tunnel_name": "${TUNNEL_NAME}",
  "tunnel_id": "${TUNNEL_ID}",
  "hostname": "${HOSTNAME}",
  "local_url": "${LOCAL_URL}",
  "access_email": "${ACCESS_EMAIL}",
  "unit": "watch-tower-tunnel.service",
  "updated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
echo "Wrote stamp → job_engine/.data/cloudflare_tunnel.json (gitignored)"
